config/routes.rb
Rails.application.routes.draw do
  resources :toothbrushes do
    resources :bookings, only: [:new, :create]
  end
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: "pages#dashboard"
  post '/accept/:id', to: "bookings#accept", as: :accept
  post '/reject/:id', to: "bookings#reject", as: :reject
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :toothbrush
  validates :status, inclusion: { in: %w(pending available rented) }
end

app/models/toothbrush.rb
class Toothbrush < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :toothbrushes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def create
    @toothbrush = Toothbrush.find(params[:toothbrush_id])
    @booking = Booking.new(booking_params)
    @booking.toothbrush = @toothbrush
    @booking.user = current_user

    @booking.status = "pending"
    if @booking.save
      redirect_to dashboard_path
    else
      render 'toothbrushes/show', status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "rented")
    redirect_to dashboard_path, notice: "Your toothbrush is booked !"
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(status: "available")
    redirect_to dashboard_path, notice: "Your toothbrush is available !"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @my_bookings = current_user.bookings
    @toothbrushes = current_user.toothbrushes
  end

  private

  def toothbrush_params
    params.require(:toothbrush).permit(:category, :content, :title, :price, :photo)
  end
end

app/controllers/toothbrushes_controller.rb
class ToothbrushesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:category] == "Electric"
      @toothbrushes = Toothbrush.where("category ILIKE ?", "Electric")
    elsif params[:category] == "Standard"
      @toothbrushes = Toothbrush.where("category ILIKE ?", "Standard")
    else
      @toothbrushes = Toothbrush.all
    end
    @toothbrushes_minus = @toothbrushes.order(:price)
    @toothbrushes_plus = @toothbrushes.order(price: :desc)
  end

  def show
    # @review = Review.new
    @toothbrush = Toothbrush.find(params[:id])
    @booking = Booking.new
  end

  def new
    @toothbrush = Toothbrush.new
  end

  def create
    @toothbrush = Toothbrush.new(toothbrush_params)
    @toothbrush.user = current_user
    if @toothbrush.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @toothbrush = Toothbrush.find(params[:id])

    if @toothbrush.update(toothbrush_params)
      redirect_to dashboard_path, notice: "Toothbrush updated"
    else
      render :dasboard, status: :unprocessable_entity
    end
  end

  def destroy
    @toothbrush = Toothbrush.find(params[:id])
    @toothbrush.destroy
    redirect_to root_path
  end

  private

  def toothbrush_params
    params.require(:toothbrush).permit(:category, :content, :title, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="my-5">
    <div data-controller="dynamic-booking-price" data-dynamic-booking-price-price-value="<%= @toothbrush.price %>">
    <%= simple_form_for [@toothbrush, @booking], html: { data: { controller: 'datepicker' }} do |f| %>
      <%= f.input :start_date, as: :string, input_html: { data: { datepicker_target: 'startDateInput', dynamic_booking_price_target: 'startDateInput', action: 'change->dynamic-booking-price#updatePrice' }, class: "rounded-3 bg-white" } %>
      <%= f.input :end_date,  as: :string, input_html: { data: {  datepicker_target: 'endDateInput', dynamic_booking_price_target: 'endDateInput', action: 'change->dynamic-booking-price#updatePrice' }, class: "rounded-3 bg-white" } %>
      <div class="position-absolute top-50 start-50 translate-middle">
      <%= f.submit "Book it", class: 'btn btn-primary' %>
      <p>
        <span data-dynamic-booking-price-target="priceHolder"></span>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DIRTYToothbrushes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,700;1,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container-dashboard">
  <div class="row justify-content-center">
    <ul class="nav nav-tabs">
      <div class="col-6">
        <li class="nav-item text-center my-3 d-flex flex-column align-items-center">
          <button class="btn-game mb-4">
            <a class="nav-link active button_top" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings" type="button" role="tab" aria-controls="bookings" aria-selected="true">My Bookings</a>
          </button>
        </li>
      </div>
      <div class="col 6">
        <li class="nav-item text-center my-3 d-flex flex-column align-items-center">
          <button class="btn-game mb-4">
            <a class="nav-link button_top" id="toothbrush-tab" data-bs-toggle="tab" data-bs-target="#toothbrush" type="button" role="tab" aria-controls="toothbrush" aria-selected="true">My Toothbrushes</a>
          </button>
        </li>
      </div>
    </ul>
  <div class="row justify-content-center">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">
        <div class="cards">
          <% @my_bookings.each do |booking| %>
            <%= link_to toothbrush_path(booking.toothbrush), class: "image-hover w-80" do %>
              <div class="card-trip my-3">
                <% if booking.toothbrush.photo.attached? %>
                  <%= cl_image_tag booking.toothbrush.photo.key, height: 130, width: 180, crop: :fill, class: "img-home" %>
                <% end %>
                <div class="card-trip-infos-dashboard">
                  <h2 class="card-trip-title"> <%=booking.toothbrush.title%> </h2>
                  <h2 class="card-trip-pricing"><%= booking.toothbrush.price %> €</h2>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
        <div class="tab-pane fade show" id="toothbrush" role="tabpanel" aria-labelledby="toothbrush-tab">
          <div class="row justify-content-center align-items-center mb-5">
            <div class= "container-tooth">
              <h2 class="fw-bold title-blue py-3">Manage my bookings</h2>
              <% @toothbrushes.each do |toothbrush| %>
              <div class="col 6">
                <div class="card-trip my-3">
                  <%= cl_image_tag toothbrush.photo.key, height: 300, width: 400, crop: :fill %>
                  <div class="card-trip-infos-dashboard">
                    <h2 class="card-trip-title"> <%=toothbrush.title%> </h2>
                    <h2 class="card-trip-pricing"><%= toothbrush.price %> €</h2>
                  </div>
                </div>
              </div>
              <div class="col 6">
                <%= simple_form_for(toothbrush) do |f| %>
                  <%= f.input :title, input_html:{ class: 'input-text rounded-5', placeholder: "Title"} %>
                  <%= f.input :category, collection: ['Electric', 'Standard'], include_blank: 'Select Category', input_html:{class: 'input-select rounded-5 bg-white'} %>
                  <%= f.input :price, input_html: { step: 'any', class: 'input-text rounded-5', placeholder: 'Price (in €)' } %>
                  <%= f.button :submit, "Save", class: 'btn rainbow show-btn' %>
                <% end %>
              </div>
            <div>
          </div>
            <div class= "container-tooth text-center">
            <h2 class="fw-bold title-blue my-4">Manage my bookings</h2>
            <% toothbrush.bookings.each do |booking| %>
              <div class="trip-date"></div>
                <div class="card-trip my-3">
                  <%= cl_image_tag booking.toothbrush.photo.key, height: 300, width: 400, crop: :fill %>
                  <div class="card-trip-infos-dashboard">
                    <h2 class="card-trip-title"> <%=booking.toothbrush.title%> </h2>
                    <h2 class="card-trip-pricing"><%= booking.toothbrush.price %> €</h2>
                  </div>
                </div>
                <%# <%= booking.start_date %>
                <%# <%= booking.end_date %>
                <h3><em class="title-blue">Total: <%= ((booking.end_date - booking.start_date) * booking.toothbrush.price).to_i %> €<em><h3>
                <% if booking.status == "pending"%>
                  <%= button_to "accept", accept_path(booking), class: "btn rainbow show-btn" %>
                  <%= button_to "reject", reject_path(booking), class: "btn rainbow show-btn" %>
                <% else %>
                  <%= booking.status %>
                <% end %>
              <% end %>
            <div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<section class="hero">
  <header id="header">
  </header>
  <header class="hero-header d-flex flex-column justify-content-center">
    <h1 class="hero-title">Like<span>Toothbrushes ?</span><h1>
    <h1 class="hero-subtitle" data-controller="typed"></h1>
  </header>
  <footer class="hero-footer">
    <%= link_to 'View Toothbrushes', toothbrushes_path, class: "btn rainbow home-btn" %>
    <%= link_to 'Rent my Toothbrush', new_toothbrush_path, class: "btn rainbow home-btn" %>
  </footer>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible fade show m-1" role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_formtest.html.erb
  <div class="container">
    <div class="mb-3 mt-3">
        <%= simple_form_for @toothbrush do |f| %>
          <%= f.input :category %>
          <%= f.input :price %>
          <%= f.input :photo %>
          <%= f.submit class:"btn" %>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dhngy6nkx/image/upload/v1685535652/toothbrush_logo.png", style: "transform: scaleX(-1) rotate(-22.5deg);" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "Home", "#", class: "nav-link" %>
          <%# </li> %>
          <% if current_page?(root_path) || current_page?(dashboard_path) %>
          <li class="nav-item">
            <%= link_to "Add", new_toothbrush_path, class:"btn rainbow home-btn-add" %>
          </li>
          <% end %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-chevron-down" style="color: #2d8cf0"></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "DashBoard", "dashboard", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/toothbrushes/destroy.html.erb
<h1>Toothbrush#destroy</h1>
<p>Find me in app/views/toothbrush/destroy.html.erb</p>

app/views/toothbrushes/edit.html.erb
<h1>Toothbrush#edit</h1>
<p>Find me in app/views/toothbrush/edit.html.erb</p>

app/views/toothbrushes/index.html.erb
<div class="container">
  <div data-controller="toggle-price">
    <div class="d-flex justify-content-around py-5">
      <%= link_to toothbrushes_path(category: "Standard") do %>
        <i class="fa-solid fa-glass-water-droplet fa-lg" style="color: #1d355d;"></i>
      <% end %>
      <!-- Button trigger modal -->
      <button type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" style="background-color: transparent; border:none;">
        <i class="fa-solid fa-bolt fa-shake fa-lg" style="color: #ec5fe1;"></i>
      </button>
      <label class="switch text-end">
        <input type="checkbox" class="toggle" data-action="change->toggle-price#toggleSwitch" data-toggle-price-target="checkbox">
        <span class="slider"></span>
        <span class="card-side"></span>
      </label>
    </div>
    <div class="cards " data-toggle-price-target="minusPrice">
      <% @toothbrushes_minus.each do |toothbrush|%>
        <%= link_to toothbrush_path(toothbrush), class: "image-hover" do %>
          <div class="card-trip">
          <% if toothbrush.photo.attached? %>
            <%= cl_image_tag toothbrush.photo.key, height: 130, width: 180, crop: :fill, class: "img-home" %>
          <% end %>
            <div class="card-trip-infos">
              <h2 class="card-trip-title"> <%=toothbrush.title%> </h2>
              <h2 class="card-trip-pricing"><%= toothbrush.price %> €</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="cards d-none" data-toggle-price-target="plusPrice">
      <% @toothbrushes_plus.each do |toothbrush|%>
        <%= link_to toothbrush_path(toothbrush), class: "image-hover" do %>
          <div class="card-trip">
          <% if toothbrush.photo.attached? %>
            <%= cl_image_tag toothbrush.photo.key, height: 130, width: 180, crop: :fill, class: "img-home" %>
          <% end %>
            <div class="card-trip-infos">
              <h2 class="card-trip-title"> <%=toothbrush.title%> </h2>
              <h2 class="card-trip-pricing"><%= toothbrush.price %> €</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #EFA3C8;">
        <h1 class="modal-title fs-5 text-center text-white" id="staticBackdropLabel" style="flex-grow: 1">⛔️ EXPLICIT CONTENT ⛔️</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div class="modal-body" style="background-color: #FAD3E7;">
          <p class="modal-title fs-5 lead text-center" id="staticBackdropLabel">Dirty T Electric offers adult content, which is intended for users above 18 years old.</p>
          <p class="modal-title fs-5 lead text-center" id="staticBackdropLabel">By continuing, you certify that you are over 18 years old.</p>
        </div>
      <div class="modal-footer" style="background-color: #FAD3E7;">
        <%= link_to toothbrushes_path(category: "Electric") do %>
          <button class="btngay">I certify that I am 18 years old or older - Enter</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/toothbrushes/new.html.erb
<div class="container">
  <div class="my-5">
  <h1 class="fw-semibold title-blue">Add your Toothbrush</h1>
  <div style="width:100%;height:0;padding-bottom:100%;position:relative;"><iframe src="https://giphy.com/embed/qrG427cL1eCt2JbuuG" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/stickers/cooneyorthodontics-transparent-qrG427cL1eCt2JbuuG"></a></p>
      <%= simple_form_for(@toothbrush) do |f| %>
        <%= f.input :title, input_html:{ class: 'input-text rounded-5', placeholder: "Title"} %>
        <%= f.input :category, collection: ['Electric', 'Standard'], include_blank: 'Select Category', input_html:{class: 'input-select rounded-5 bg-white'} %>
        <%= f.input :price, input_html: { step: 'any', class: 'input-text rounded-5', placeholder: 'Price (in €)' } %>
        <%= f.input :photo, as: :file, input_html: {class: 'input-photo rounded-5 bg-white'} %>
        <%= f.submit "Create", class: 'btn rainbow show-btn'%>
      <% end %>
  </div>
</div>

app/views/toothbrushes/show.html.erb
<div class="row justify-content-center">
  <div class="col-10 col-md-4 card shadow zoom">
    <div class="card-body">
      <h2 class="card-title mb-4 text-center title-blue mt-2 fw-bold"><%= @toothbrush.title %></h2>
      <div class="cd-img-top text-center">
          <%= cl_image_tag @toothbrush.photo.key, height: 400, width: 400, crop: :fill, class: "img-fluid m-4 imgshow" %>
      </div>
      <div class="m-2">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="row">
              <div class="col">
                <h5 class="m-0">Category:</h5 class="m-0">
              </div>
              <div class="col">
                <h5 class="m-0"><%= @toothbrush.category %></h5 class="m-0">
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col">
                <h5 class="m-0">Price:</h5 class="m-0">
              </div>
              <div class="col">
                <h5 class="m-0"><%= @toothbrush.price %> €</h5 class="m-0">
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col">
                <h5 class="m-0">Content:</h5 class="m-0">
              </div>
              <div class="col">
                <h5 class="m-0"><%= @toothbrush.content %></h5 class="m-0">
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="d-flex justify-content-between m-2">
      <%= link_to 'Home', toothbrushes_path, class: "btn rainbow show-btn" %>
      <button type="button" class="btn rainbow show-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Book it
      </button>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">booking</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for [@toothbrush, @booking], html: { data: { controller: 'datepicker' }} do |f| %>
      <div class="modal-body">
        <div data-controller="dynamic-booking-price" data-dynamic-booking-price-price-value="<%= @toothbrush.price %>">
          <%= f.input :start_date, as: :string, input_html: { data: { datepicker_target: 'startDateInput', dynamic_booking_price_target: 'startDateInput', action: 'change->dynamic-booking-price#updatePrice' }, class: "round" } %>
          <%= f.input :end_date,  as: :string, input_html: { data: {  datepicker_target: 'endDateInput', dynamic_booking_price_target: 'endDateInput', action: 'change->dynamic-booking-price#updatePrice' } } %>
          <p>
            <span data-dynamic-booking-price-target="priceHolder"></span>
          </p>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Book now !", class: 'btn rainbow show-btn' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/toothbrushes/update.html.erb
<h1>Toothbrush#update</h1>
<p>Find me in app/views/toothbrush/update.html.erb</p>